Modify appengine_deploy template in order to use `gcloud` for deployment instead of `appcfg.sh`

diff --git a/appengine/java/appengine_deploy.sh.template b/appengine/java/appengine_deploy.sh.template
--- a/appengine/java/appengine_deploy.sh.template
+++ b/appengine/java/appengine_deploy.sh.template
@@ -33,13 +33,18 @@ ${JAVA_RUNFILES}/%{zipper} x ${JAVA_RUNFILES}/%{war}
 cd ${root_dir}
 
 APP_ENGINE_ROOT=${JAVA_RUNFILES}/%{appengine_sdk}
-if [ -n "${1-}" ]; then
-  ${APP_ENGINE_ROOT}/bin/appcfg.sh -A "$1" update ${tmp_dir}
-  retCode=$?
-else
-  ${APP_ENGINE_ROOT}/bin/appcfg.sh update ${tmp_dir}
-  retCode=$?
+
+if [ $# -lt 2 ]; then
+	echo "ERROR: projectId/appId and version should be provided as arguments"
+	exit
 fi
+
+if [ $# -gt 2 ]; then
+	echo "WARN: Some arguments are not used"
+fi
+
+gcloud app deploy "${tmp_dir}/WEB-INF/appengine-web.xml" --project="${1}" --version="${2}" --no-promote --quiet
+retCode=$?
 
 rm -rf ${tmp_dir}
 trap - EXIT
